name: Test

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno test

      - name: Check formatting
        run: deno fmt --check

      - name: Check linting
        run: deno lint

      - name: Type check
        run: deno check mod.ts

      - name: Dry run publish to JSR
        run: deno publish --dry-run
